# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOSProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOSProject
  pod 'FlutterEngine', :path => '../FlutterEngine'


  target 'IOSProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOSProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
